sudo: false
language: node_js
node_js:
- iojs
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: U6ewdYTSrJE74rgXYklxCZ0dr/MeMJ2Z1u2iiVL8G98rR9c1Jx/Q+qtd1E+/PuE+p+/fHAZ1WruYBaJCMu6vOf4lB3Jam1OElh1LtPDdkDpKJGvAVcn4EShbh+aRfn7yWvSYExbBOYGfFiNpU7Gfag//0BkqApOMVswF8HyJXLskQ2uhHWZ4Qzza2CGIFGOmWGxwpUYhs1ms/HZZZ4IqFvV38tbT2AMXi6BPTfW+bgBAZ465JupwU9/eWgIsy1cXJgUOmIml71QC+2ckoIci4ghcj1s/XlomrCplroc/pUX0RC6szJFtDyVJ5CbQt4JvXu8QKOKlBkb/z+Ln5NJUjrfpj094QHPngY7muYAowaVt24lJAfxMa2k7lbgzcUfN7kCSU2rMyT7kcjm52ZkzxVHMjjYzoHD5JnaVvchgGqYSLV4Hzt3gb9prXkhE4C0WgDcgibGc+FbHEMWgsk5nUV/6ruiwtlokdPlLX8toSH99iE0IdhK0EZ1KjPDNJa9pKPwyGzGE0h6qSnKrpl5H3cwd2CBoaPAXDa7eIugHtkdPQ3kO00TseDE2qXhbCiEV6XWwh3L9whSyJjLnvICcCxOvgXlJGqBq8PnjQEk/3Q3nlCZlmuzLUttqzWeNkuuUEp6KIxvueN7fxT71aP1cYoCP8NMceRITlCh0wzrLRSY=
  on:
    tags: true
    repo: Brightspace/node-auth-token
